### ISSUE TITLE
Launching with head

### ISSUE THREAD

**Issue by Schizo** [frenchmatt/RTSPStreaming#1]
I was wondering if this plugin was only designed for headless use? What If I actually just wan't to run and stream it to another device/sink within the editor when I hit play? I wasn't able to find any reference to that. 

Thanks for the detailed explanation, I run exactly into a FAQ issue and it took me a minute to solve!

**Comment by frenchmatt** [comment]
Thanks so much for checking out the project! 

This plugin was designed for headless use but disabling headless mode is possible. See the Testing section of [Setup and Usage Guide](https://github.com/frenchmatt/RTSPStreaming/blob/master/SetupUsageGuide.md) for information on how to control those options. 

For now, the game must be packaged to stream. There is no support for streaming from the editor.

I also want to make sure you are aware that this plugin was being built for an older version of the engine (4.22) and may not work in newer versions.

**Comment by Schizo** [comment]
@frenchmatt Thanks for your quick answer. Was there a limitation of running it from the editor, or you just didn't tailor it for it? I'm looking for a solution to access the *framebuffer* when you hit the `play` button so I can later create a video from the live "fly over".

**Comment by frenchmatt** [comment]
@Schizo just as the PixelStreaming plugin must be used in a packaged game, so too does this plugin. The initialization of either of these modules does not happen when pressing `play` in the editor. I am unsure why Epic built the Pixel Streamer that way, but it was easiest to use the same initialization to build this plugin.

This plugin certainly allows access to that buffer. It would be pretty easy to modify this project to also enable saving the video instead of streaming. If I remember correctly, that was one capability I removed early on because it was not useful to me at the time.
